# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{object-send}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kim Burgestrand"]
  s.date = %q{2010-08-01}
  s.description = %q{What is send?
=============
It’s a tiny wee ruby gem that is a fork of [Object#try](http://ozmm.org/posts/try.html)
and [Object#try from Rails](http://api.rubyonrails.org/classes/Object.html#M000027). It will *never* throw a NoMethodError (no matter the receiver), and returns nil
if called on a nil-class or if the method in the receiver does not exist.

Note on Patches/Pull Requests
-----------------------------

1. [Fork me!](http://github.com/Burgestrand/send-/fork)
2. Write tests for your new feature or bug fix (important, I don’t want
   to break your stuff in a future update by accident!)
3. Hack away on the code; make your tests pass.
4. Commit! Don’t touch Rakefile, version or git history in any of the 
   commits you want me to pick.
5. ???
6. Send me a pull request!
}
  s.email = %q{kim@burgestrand.se}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/object/send.rb",
     "object-send.gemspec",
     "spec/send_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/Burgestrand/send?}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{object-send}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Object#send? similar to Object#try?, but works for nil and with arguments.}
  s.test_files = [
    "spec/send_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

